// ════════════════════════════════════════════════════════════════════════════
// CES ENTERPRISE OPERATIONS SYSTEM — automation.gs
// Core Automation Engine — 8 active rules
// Last updated: May 2026 — v3.0 (Finance & Payment rules removed)
// ════════════════════════════════════════════════════════════════════════════

// ── ENTRY POINTS (called by time-based triggers) ──────────────────────────────

function runDailyAutomations() {
  dailyOperationsReport();   // AUTO-001
  checkInventoryAlerts();    // AUTO-002
  checkEventReminders48hr(); // AUTO-007
  checkPostEventDebrief();   // AUTO-008
  updateEventHealthScores(); // AUTO-006
  auditLog('DAILY_AUTOMATIONS_RUN', 'Automation', '', '', 'All 4 daily rules completed');
}

function runWeeklyAutomations() {
  weeklyExecutiveReport();   // AUTO-005
  auditLog('WEEKLY_REPORT_SENT', 'Automation', '', '', 'Completed');
}

// ── AUTO-001: DAILY OPERATIONS REPORT ────────────────────────────────────────
function dailyOperationsReport() {
  const events  = getSheetData_('01_Events_Master');
  const today   = Utilities.formatDate(new Date(), Session.getScriptTimeZone(), 'yyyy-MM-dd');

  const todayEvts  = events.filter(e => String(e['Event Date']).startsWith(today));
  const activeEvts = events.filter(e => ['Active','Confirmed'].includes(e['Status']));
  const lowHealth  = events.filter(e => Number(e['Health Score']) < 65 && e['Status'] !== 'Completed');

  const subject = `[CES] Daily Operations Report — ${today}`;
  const body = `
CREATIVE EVENT SERVICES — DAILY OPERATIONS REPORT
${today}
${'═'.repeat(50)}

TODAY'S EVENTS (${todayEvts.length})
${todayEvts.map(e => `• ${e['Event ID']} | ${e['Event Name']} | ${e['Venue Name']} | Setup: ${e['Setup Time']} → Strike: ${e['Strike Time']}`).join('\n') || '• No events today'}

ACTIVE & CONFIRMED EVENTS (${activeEvts.length})
${activeEvts.map(e => `• ${e['Event ID']} | ${e['Event Name']} | ${e['Status']} | Health: ${e['Health Score']}% | Manager: ${e['Event Manager']}`).join('\n') || '• None'}

⚠️ LOW HEALTH ALERTS (${lowHealth.length})
${lowHealth.map(e => `• ${e['Event ID']} | ${e['Event Name']} | Health: ${e['Health Score']}% | Risk: ${e['Risk Level']}`).join('\n') || '• None — all events healthy'}

${'─'.repeat(50)}
Generated by CES Automation Engine v3.0 | ${new Date().toLocaleString()}
  `.trim();

  sendEmail_(getSetting_('OWNER_EMAIL'), subject, body);
  sendEmail_(getSetting_('OPERATIONS_EMAIL'), subject, body);
  logNotification_('DAILY_REPORT', getSetting_('OWNER_EMAIL'), subject, 'Email', 'Sent');
  updateAutoConfig_('AUTO-001');
}

// ── AUTO-002: INVENTORY ALERT ─────────────────────────────────────────────────
function checkInventoryAlerts() {
  const inventory = getSheetData_('05_Inventory_Master');
  const alerts = [];

  inventory.forEach(function(item) {
    if (item['Status'] === 'In Repair') {
      alerts.push(`🔧 IN REPAIR: ${item['Item ID']} — ${item['Item Name']} | Condition: ${item['Condition']} | Location: ${item['Location']}`);
    }
    if (Number(item['Available']) === 0 && item['Status'] !== 'In Repair') {
      alerts.push(`📦 UNAVAILABLE: ${item['Item ID']} — ${item['Item Name']} | All ${item['Quantity']} units deployed`);
    }
  });

  if (alerts.length > 0) {
    const subject = `[CES] ⚠️ Inventory Alert — ${alerts.length} Issue(s)`;
    const body = `INVENTORY ALERT\n\n${alerts.join('\n')}\n\nPlease review and update inventory status in the dashboard.\n\nCES Automation Engine`;
    sendEmail_(getSetting_('OPERATIONS_EMAIL'), subject, body);
    logNotification_('INVENTORY_ALERT', getSetting_('OPERATIONS_EMAIL'), subject, 'Email', 'Sent');
  }
  updateAutoConfig_('AUTO-002');
}

// ── AUTO-003: STAFF ASSIGNMENT NOTIFICATION (called manually on assignment) ───
function notifyStaffAssignment(staffEmail, staffName, eventName, eventDate, venue, manager) {
  const subject = `[CES] ✅ You've Been Assigned — ${eventName}`;
  const body = `Hi ${staffName},\n\nYou have been assigned to the following event:\n\nEvent:   ${eventName}\nDate:    ${eventDate}\nVenue:   ${venue}\nManager: ${manager}\n\nPlease confirm your availability by replying to this email.\n\nIf you have any questions, contact your Event Manager directly.\n\nThank you,\nCreative Event Services — Operations Team`;
  sendEmail_(staffEmail, subject, body);
  logNotification_('STAFF_ASSIGNMENT', staffEmail, subject, 'Email', 'Sent');
  updateAutoConfig_('AUTO-003');
}

// ── AUTO-005: WEEKLY EXECUTIVE REPORT ─────────────────────────────────────────
function weeklyExecutiveReport() {
  const events    = getSheetData_('01_Events_Master');
  const staff     = getSheetData_('03_Staff_Master');
  const inventory = getSheetData_('05_Inventory_Master');
  const logistics = getSheetData_('07_Logistics');

  const total     = events.length;
  const active    = events.filter(e => e['Status'] === 'Active').length;
  const confirmed = events.filter(e => e['Status'] === 'Confirmed').length;
  const completed = events.filter(e => e['Status'] === 'Completed').length;
  const avgHealth = total ? Math.round(events.reduce((s,e) => s + (Number(e['Health Score'])||0), 0) / total) : 0;
  const inRepair  = inventory.filter(i => i['Status'] === 'In Repair').length;
  const avgPerf   = staff.length ? Math.round(staff.reduce((s,m) => s + (Number(m['Performance Score'])||0), 0) / staff.length) : 0;

  const dateStr = Utilities.formatDate(new Date(), Session.getScriptTimeZone(), 'MMM dd, yyyy');
  const subject = `[CES] 📊 Weekly Executive Report — ${dateStr}`;
  const body = `
CREATIVE EVENT SERVICES — WEEKLY EXECUTIVE REPORT
${dateStr}
${'═'.repeat(50)}

EVENTS SUMMARY
Total Events:     ${total}
Active Now:       ${active}
Confirmed:        ${confirmed}
Completed:        ${completed}
Avg Health Score: ${avgHealth}%

OPERATIONS
Staff Members:    ${staff.length}
Avg Performance:  ${avgPerf}%
Items In Repair:  ${inRepair}
Total Dispatches: ${logistics.length}

UPCOMING THIS WEEK
${events.filter(e => ['Active','Confirmed','Planning'].includes(e['Status'])).slice(0,5).map(e => `• ${e['Event Name']} | ${e['Event Date']} | ${e['Status']}`).join('\n') || '• None this week'}

${'─'.repeat(50)}
Generated: ${new Date().toLocaleString()}
CES Enterprise Operations System v3.0
  `.trim();

  sendEmail_(getSetting_('OWNER_EMAIL'), subject, body);
  logNotification_('WEEKLY_REPORT', getSetting_('OWNER_EMAIL'), subject, 'Email', 'Sent');
  updateAutoConfig_('AUTO-005');
}

// ── AUTO-006: EVENT HEALTH SCORE UPDATE ───────────────────────────────────────
function updateEventHealthScores() {
  const ss           = SpreadsheetApp.getActiveSpreadsheet();
  const eventsSheet  = ss.getSheetByName('01_Events_Master');
  if (!eventsSheet) return;

  const events = getSheetData_('01_Events_Master');

  events.forEach(function(evt, i) {
    let score = 100;

    // Staff assigned?
    const staffList = String(evt['Staff Assigned'] || '').split(',').filter(Boolean);
    if (staffList.length === 0) score -= 25;
    else if (staffList.length < 2) score -= 10;

    // Truck assigned?
    if (!evt['Truck Assigned'] || evt['Truck Assigned'] === '—') score -= 10;

    // Risk level
    if (evt['Risk Level'] === 'High')   score -= 15;
    else if (evt['Risk Level'] === 'Medium') score -= 5;

    // Inventory reserved?
    const invList = String(evt['Inventory Reserved'] || '').split(',').filter(Boolean);
    if (invList.length === 0) score -= 10;

    score = Math.max(0, Math.min(100, score));

    // Health Score is column 16 (index 15, row = i+2)
    eventsSheet.getRange(i + 2, 16).setValue(score);
  });

  logNotification_('HEALTH_UPDATE', 'System', 'Health scores recalculated for all events', 'System', 'Completed');
  updateAutoConfig_('AUTO-006');
}

// ── AUTO-007: EVENT REMINDER — 48 HOURS ──────────────────────────────────────
function checkEventReminders48hr() {
  const events  = getSheetData_('01_Events_Master');
  const now     = new Date();
  const in48hrs = new Date(now.getTime() + 48 * 60 * 60 * 1000);

  events.forEach(function(evt) {
    if (!['Active','Confirmed'].includes(evt['Status'])) return;
    const evtDate = new Date(evt['Event Date']);
    if (isNaN(evtDate)) return;

    // Check if event is within next 48 hours
    if (evtDate >= now && evtDate <= in48hrs) {
      const manager = evt['Event Manager'] || getSetting_('OPERATIONS_EMAIL');
      const subject = `[CES] ⏰ 48-Hour Reminder — ${evt['Event Name']}`;
      const body = `Hi ${evt['Event Manager']},\n\nThis is your 48-hour reminder for the upcoming event:\n\nEvent:   ${evt['Event Name']}\nDate:    ${evt['Event Date']}\nVenue:   ${evt['Venue Name']}\nSetup:   ${evt['Setup Time']}\nStrike:  ${evt['Strike Time']}\nStatus:  ${evt['Status']}\n\nChecklist:\n□ Staff confirmed\n□ Truck loaded and ready\n□ Inventory checked out\n□ Client briefed\n□ Venue access confirmed\n\nPlease ensure all preparations are complete.\n\nCES Automation Engine`;
      sendEmail_(getSetting_('OPERATIONS_EMAIL'), subject, body);
      logNotification_('EVENT_REMINDER_48HR', getSetting_('OPERATIONS_EMAIL'), subject, 'Email', 'Sent');
    }
  });
  updateAutoConfig_('AUTO-007');
}

// ── AUTO-008: POST-EVENT DEBRIEF ──────────────────────────────────────────────
function checkPostEventDebrief() {
  const events = getSheetData_('01_Events_Master');
  const now    = new Date();

  events.forEach(function(evt) {
    if (evt['Status'] !== 'Completed') return;
    const strikeTime = new Date(evt['Event Date'] + ' ' + (evt['Strike Time'] || '23:00'));
    if (isNaN(strikeTime)) return;

    const hoursSinceStrike = (now - strikeTime) / (1000 * 60 * 60);

    // Send debrief between 20–28 hours after strike (to avoid sending multiple times)
    if (hoursSinceStrike >= 20 && hoursSinceStrike <= 28) {
      const subject = `[CES] 📋 Post-Event Debrief — ${evt['Event Name']}`;
      const body = `Hi ${evt['Event Manager']},\n\nThe event has been completed. Please submit your post-event debrief:\n\nEvent:   ${evt['Event Name']}\nDate:    ${evt['Event Date']}\nVenue:   ${evt['Venue Name']}\nHealth Score: ${evt['Health Score']}%\n\nDebrief Questions:\n1. Did the event run on time? (Setup & Strike)\n2. Any staff issues to report?\n3. Any inventory damage or missing items?\n4. Client feedback received?\n5. What went well?\n6. What needs improvement for next time?\n\nPlease reply to this email with your responses.\n\nThank you,\nCES Automation Engine`;
      sendEmail_(getSetting_('OPERATIONS_EMAIL'), subject, body);
      logNotification_('POST_EVENT_DEBRIEF', getSetting_('OPERATIONS_EMAIL'), subject, 'Email', 'Sent');
    }
  });
  updateAutoConfig_('AUTO-008');
}

// ── HELPERS ───────────────────────────────────────────────────────────────────

function sendEmail_(to, subject, body) {
  if (!to || !to.includes('@')) return;
  try {
    GmailApp.sendEmail(to, subject, body);
  } catch(err) {
    auditLog('EMAIL_FAILED', 'Automation', '', to, err.message);
  }
}

function getSheetData_(sheetName) {
  const ss    = SpreadsheetApp.getActiveSpreadsheet();
  const sheet = ss.getSheetByName(sheetName);
  if (!sheet || sheet.getLastRow() < 2) return [];
  const data    = sheet.getDataRange().getValues();
  const headers = data[0];
  return data.slice(1).map(function(row) {
    const obj = {};
    headers.forEach(function(h, i) { obj[h] = row[i]; });
    return obj;
  });
}

function getSetting_(key) {
  const settings = getSheetData_('11_Admin_Settings');
  const row = settings.find(function(s) { return s['Key'] === key; });
  return row ? String(row['Value']) : '';
}

function logNotification_(type, recipient, message, channel, status) {
  const s = SpreadsheetApp.getActiveSpreadsheet().getSheetByName('08_Notifications');
  if (!s) return;
  s.appendRow(['NOTIF-' + new Date().getTime(), type, recipient, message, channel, status, new Date(), '', '']);
}

function updateAutoConfig_(autoId) {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const s  = ss.getSheetByName('09_Automation_Config');
  if (!s || s.getLastRow() < 2) return;
  const data = s.getDataRange().getValues();
  for (let i = 1; i < data.length; i++) {
    if (data[i][0] === autoId) {
      s.getRange(i + 1, 6).setValue(new Date()); // Last Run
      s.getRange(i + 1, 7).setValue((Number(data[i][6]) || 0) + 1); // Run Count++
      break;
    }
  }
}

function auditLog(action, module, recordId, oldVal, newVal) {
  const s = SpreadsheetApp.getActiveSpreadsheet().getSheetByName('10_System_Logs');
  if (!s) return;
  const user = Session.getActiveUser().getEmail() || 'system';
  s.appendRow(['LOG-' + new Date().getTime(), new Date(), user, action, module, recordId || '', oldVal || '', newVal || '', '']);
}
